/* === LITURGIA.JS - BASE DE DATOS DEL CALENDARIO SANTORAL Y REZOS === */

const DescripcionesHoras = [
    "Alabanzas del amanecer. La hueste despierta con la luz de Cristo.",
    "Primera hora del día. Comienza la marcha hacia la gloria.",
    "Media mañana. El fervor y la fatiga aumentan bajo el sol.",
    "El mediodía. El sol castiga a justos y pecadores por igual.",
    "Media tarde. El cansancio se asienta, pero la fe sostiene el acero.",
    "El ocaso. La luz mengua y se elevan rezos por los caídos.",
    "La noche cae. Última oración antes del descanso en el campamento."
];

const OracionesCanonicas = {
    "Laudes": { v1: "V. Domine, labia mea aperies.", r1: "R. Et os meum annuntiabit laudem tuam.", v2: "V. Deus, in adiutorium meum intende.", r2: "R. Domine, ad adiuvandum me festina.<br><br>Gloria Patri, et Filio, et Spiritui Sancto. Sicut erat in principio, et nunc, et semper, et in saecula saeculorum. Amen. Alleluia." },
    "Prima": { v1: "V. Deus, in adiutorium meum intende.", r1: "R. Domine, ad adiuvandum me festina.", v2: "V. Dirigere et sanctificare, regere et gubernare dignare, Domine Deus.", r2: "R. Corda et corpora nostra in lege tua, et in operibus mandatorum tuorum. Amen." },
    "Tercia": { v1: "V. Deus, in adiutorium meum intende.", r1: "R. Domine, ad adiuvandum me festina.", v2: "V. Nunc, Sancte, nobis, Spiritus, unum Patri cum Filio.", r2: "R. Dignare promptus ingeri, nostro refusus pectori. Amen." },
    "Sexta": { v1: "V. Deus, in adiutorium meum intende.", r1: "R. Domine, ad adiuvandum me festina.", v2: "V. Rector potens, verax Deus, qui temperas rerum vices.", r2: "R. Extingue flammas litium, aufer calorem noxium. Amen." },
    "Nona": { v1: "V. Deus, in adiutorium meum intende.", r1: "R. Domine, ad adiuvandum me festina.", v2: "V. Rerum Deus tenax vigor, immotus in te permanens.", r2: "R. Lucis diurnae tempora successibus determinans. Amen." },
    "Vísperas": { v1: "V. Deus, in adiutorium meum intende.", r1: "R. Domine, ad adiuvandum me festina.", v2: "V. Dirigatur, Domine, oratio mea.", r2: "R. Sicut incensum in conspectu tuo. Amen." },
    "Completas": { v1: "V. Iube, domne, benedicere. Noctem quietam et finem perfectum concedat nobis Dominus omnipotens. Amen.<br>V. Converte nos, Deus, salutaris noster.", r1: "R. Et averte iram tuam a nobis.", v2: "V. Deus, in adiutorium meum intende.", r2: "R. Domine, ad adiuvandum me festina.<br><br>Gloria Patri et Filio, et Spiritui Sancto. Sicut erat in principio, et nunc, et semper, et in saecula saeculorum. Amen." }
};

const OracionesEspeciales = {
    divinasAlabanzas: "Benedictus Deus.<br>Benedictum Nomen Sanctum eius.<br>Benedictus Iesus Christus, verus Deus et verus homo.<br>Benedictum Nomen Iesu.<br>Benedictum Cor eius sacratissimum.<br>Benedictus Sanguis eius pretiosissimus.<br>Benedictus Iesus in sanctissimo altaris Sacramento.<br>Benedictus Sanctus Spiritus, Paraclitus.<br>Benedicta excelsa Mater Dei, Maria sanctissima.<br>Benedicta sancta eius et immaculata Conceptio.<br>Benedicta eius gloriosa Assumptio.<br>Benedictum nomen Mariae, Virginis et Matris.<br>Benedictus sanctus Ioseph, eius castissimus Sponsus.<br>Benedictus Deus in Angelis et in Sanctis suis. Amen.",
    veniSancteSpiritus: "Veni, Sancte Spíritus, reple tuórum corda fidélium, et tui amóris in eis ignem accénde. Emítte Spíritum tuum et creabúntur. Et renovábis fáciem terræ.<br><br>Orémus: Deus, qui corda fidélium Sancti Spíritus illustratióne docuísti, da nobis in eódem Spíritu recta sápere, et de eius semper consolatióne gaudére. Per Christum Dóminum nostrum. Amen."
};

const CalendarioSantoral = [
    { fecha: "17 de Diciembre de 1198", santo: "San Lázaro de Betania", biografia: "nuestro Señor lloró ante su tumba antes de arrancarlo de las garras de la muerte? Así como la carne de Lázaro hedía a podredumbre, así hiede el alma en pecado mortal. Solo la voz de Cristo puede ordenar a un alma muerta que salga de su sepulcro de vicios." }, 
    { fecha: "18 de Diciembre de 1198", santo: "la Expectación del Parto de Nuestra Señora", biografia: "Nuestra Señora aguardaba con perfecta pureza el nacimiento del Redentor? En este mundo manchado por la lujuria y la sangre, debemos imitar el vientre inmaculado de María: prepararnos en silencio, penitencia y castidad para recibir a Dios en nuestro corazón." }, 
    { fecha: "19 de Diciembre de 1198", santo: "San Anastasio, Papa", biografia: "este Santo Pontífice fue un azote contra la herejía. No hubo falsa misericordia en sus palabras, pues tolerar el error es odiar el alma del prójimo. Aprended, soldados: la verdad divina no se negocia, se defiende con la vida misma." }, 
    { fecha: "20 de Diciembre de 1198", santo: "Santo Domingo de Silos", biografia: "dedicó su vida a redimir cristianos cautivos por los moros? Mirad vuestras espadas; él usó la caridad para vaciar prisiones, vosotros derramáis sangre para el mismo fin. Si el corazón no arde en caridad, vuestro combate es simple carnicería." }, 
    { fecha: "21 de Diciembre de 1198", santo: "Santo Tomás, Apóstol", biografia: "su duda ofendió al Señor, pero al tocar sus santas llagas confesó: '¡Señor mío y Dios mío!'? Muchos de vosotros dudaréis cuando el miedo os hiele la sangre en batalla. Meted el dedo en la llaga del sacrificio, y que la fe venza vuestra cobardía." }, 
    { fecha: "22 de Diciembre de 1198", santo: "San Flaviano", biografia: "prefirió ser marcado con hierros candentes antes que rendir culto a los ídolos falsos? Hoy el mundo no pide que quememos incienso a estatuas, sino que adoremos el oro y el placer. Ser mártir es despreciar este mundo corrupto para ganar el eterno." }, 
    { fecha: "23 de Diciembre de 1198", santo: "Santa Victoria", biografia: "esta joven doncella rechazó un matrimonio ventajoso con un pagano para conservar su virginidad para Cristo y fue apuñalada en el corazón? Qué vergüenza para los hombres que venden su alma por unas monedas, cuando una frágil doncella entregó su vida por la pureza." }, 
    { fecha: "24 de Diciembre de 1198", santo: "Vigilia de la Natividad", biografia: "hoy es día de ayuno estricto y ceniza? No hay gozo sin preparación, ni resurrección sin cruz. Apretad el cinturón de vuestra armadura y mortificad la carne, pues el Rey de Reyes está por nacer en un pesebre humilde, no en un palacio de oro." }, 
    { fecha: "25 de Diciembre de 1198", santo: "la Natividad de Nuestro Señor Jesucristo", biografia: "el Dios inmenso se ha hecho un niño frágil, temblando de frío entre las bestias? Los reyes de la tierra se enorgullecen de sus ropajes, pero el Rey del Universo nos enseña que el orgullo es el veneno de Satanás. Humillaos, o jamás entraréis en Su Reino." }, 
    { fecha: "26 de Diciembre de 1198", santo: "San Esteban, Protomártir", biografia: "mientras las piedras destrozaban su cráneo, él rezó por sus verdugos? Es fácil matar al enemigo en la furia del combate, pero perdonar a quien te odia requiere la fuerza del Espíritu Santo. Luchad por justicia, no con odio personal, o seréis tan paganos como ellos." }, 
    { fecha: "27 de Diciembre de 1198", santo: "San Juan, Apóstol y Evangelista", biografia: "fue el único apóstol que no huyó despavorido, manteniéndose firme al pie de la Cruz? La cobardía es la marca del traidor. Cuando la batalla parezca perdida, ¿huiréis como los demás, o permaneceréis bajo la lluvia de sangre?" }, 
    { fecha: "28 de Diciembre de 1198", santo: "los Santos Inocentes", biografia: "fueron degollados por la ambición asesina de Herodes? La tiranía de los hombres siempre busca devorar la inocencia. Vuestras espadas son el escudo de los débiles. Si no protegéis a los indefensos, sois cómplices de los verdugos." }, 
    { fecha: "29 de Diciembre de 1198", santo: "Santo Tomás Becket, Obispo y Mártir", biografia: "fue asesinado a los pies del altar por esbirros de un rey terrenal? Él prefirió la muerte antes que someter la Iglesia al Estado. Ningún soberano humano está por encima de la Ley de Dios. Si un rey os ordena pecar, vuestro deber es la desobediencia sagrada." }, 
    { fecha: "30 de Diciembre de 1198", santo: "San Sabino", biografia: "le cortaron las manos por negarse a adorar a Júpiter, y aún mutilado, curaba enfermos? No hay excusa para la tibieza. Si os cortan el brazo derecho en la batalla, ofreced el izquierdo, y si perdéis ambos, ofreced vuestra sangre." }, 
    { fecha: "31 de Diciembre de 1198", santo: "San Silvestre, Papa", biografia: "bajo su pontificado cesaron las persecuciones y la Santa Iglesia emergió triunfante de las catacumbas? Todo imperio construido sobre el pecado caerá en ruinas, pero la Cátedra de Pedro permanecerá hasta el fin de los tiempos." }, 
    { fecha: "1 de Enero de 1199", santo: "la Circuncisión del Señor", biografia: "hoy el Niño Dios derramó su primera sangre por nosotros, sometiéndose a la Ley aunque era el Dueño de ella? La obediencia duele, mortifica y sangra, pero es el único camino a la santidad. Un soldado desobediente es la ruina de su propio batallón." }, 
    { fecha: "2 de Enero de 1199", santo: "San Macario de Alejandría", biografia: "huyó al desierto para mortificar su cuerpo con ayunos extremos? El peor enemigo no es el pagano que os ataca de frente, sino el demonio de la concupiscencia que os ataca desde dentro. Dominad vuestra carne, o vuestra carne os arrastrará al fuego." }, 
    { fecha: "3 de Enero de 1199", santo: "Santa Genoveva", biografia: "salvó a París de los bárbaros no con espadas, sino exhortando al pueblo a la penitencia? La oración de un alma pura detiene ejércitos enteros. No confiéis ciegamente en vuestras armaduras; la verdadera victoria se forja de rodillas." }, 
    { fecha: "4 de Enero de 1199", santo: "San Tito", biografia: "fue discípulo de San Pablo, a quien se le encomendó corregir a los herejes con dureza? La corrección fraterna es un acto de amor supremo. Si veis a un hermano pecar y calláis por falsa tolerancia, su condena será también la vuestra." }, 
    { fecha: "5 de Enero de 1199", santo: "San Telesforo, Papa y Mártir", biografia: "instituyó la Misa de Medianoche y luego fue gloriosamente martirizado? La Santa Eucaristía es el centro de nuestra existencia. Quien combate sin alimentarse del Cuerpo de Cristo, es como un árbol seco que el menor viento derriba." }, 
    { fecha: "6 de Enero de 1199", santo: "la Epifanía del Señor", biografia: "los Reyes Magos cayeron de rodillas ante la Verdad, ofreciendo oro, incienso y mirra? Rechazaron a los ídolos para adorar al único Rey. Entregad hoy vuestras riquezas materiales, la oración de vuestro espíritu y la amargura de vuestros sacrificios." } 
];